### PR TITLE
1289: Fixed issue with item value being taken from another item

### LINKED ISSUE #1289: Locked character sheet skill totals don't match the unlocked sheet or edited values
Am running the latest Foundry version 10 Build 288, and the latest Call of Cthulhu version 0.9.2.
Bug persists regardless of modules.

## Description.

Some skills added by both the example and custom setups have differing values depending on whether the sheet is locked or unlocked.
It's specific to skills added by setups and doesn't seem to apply to manually added skills. Renaming the skills fixes the "issue." Also seems specific to: Art/Craft Any, Pilot Any, Science Any and Survival Any. 

Adding a new skill to the sheet can also result in changes to bugged skills, for instance after adding a second Art/Craft Any, both Art/Crafts work properly but the Survival Any became bugged and the bugged values of Science Any and Pilot Any changed from 10 to 5.

Not big issue given how easy it is to fix but has caused me and players some confusion.

## Expected Behavior.

Art/Craft Any should be 5 not 10
Pilot Any should be 1 not 10
Science Any should be 1 not 10

Edited total values in skills tab should persist into locked sheet.
Making changes in the development tab should be totalled in the value column and show in the skill tab.

## Actual Behavior.

Skill values change when locked and unlocked. There's a unlocked value and a locked value.
Editing the value of bugged skills when unlocked does not persist when locked.
Changes made in the development tab to bugged skills do not total.

## Screenshots.

locked-sheet
unlocked-sheet
development-sheet
After adding another skill note the totals of Survival, Pilot and Science have changed:
after-changes-development
after-changes-skills

### PR DESCRIPTION
**Pull request by kwitczak**
## Motivation and Context

The goal of this change was to fix a problem described in #1289 - skills in the Character sheet had different values when the sheet was in a `locked` vs `unlocked` state. That was happening for specialised skills named "Any", for example, "Pilot (Any)" or "Art/Craft (Any)".

## Root cause
This problem is caused by the fact that we don't fully support skills with non-unique names.
Skills as items are stored in `this.system.skills` object, and there are two keys used to identify them:

- `skillName`
- `id`

And they live next to each other in the same object, `this.system.skills`.

In some cases, `skillName` is used to obtain a skill, in some cases it's `id`.
As a result, if two skills with the same name exist, their `rawValue` will be displayed correctly, while `value` will be taken from the `this.system.skills` by `skillName`, thus picking the last object that was saved with that non-unique key name, causing the problem.

## Types of Changes
I feel `id` is a new thing and I don't know if using only this property (which would be best) won't break old systems...
So I added a method which, for a given item, should either store it using `id` or, if `id` does not exists, as `skillName`.
It's also used for obtaining the item the same way.
- [ ] Fixes #1289 

## Tests Done
* Adding a skill and rolling it
* Editing a skill and rolling it
* Adding occupation to a character and rolling these skills
* Doing battle roles and dodge rolls
* Doing creature rolls

### CODE REVIEW

File: module/items/skill/data.js [hunk 1]
```diff
@@ -116,8 +125,7 @@ export class CoC7Skill extends CoC7Item {
    * This is the skill's value after active effects have been applied
    */
   get value () {
-    const value = this.parent?.system.skills?.[`${this.system.skillName}`]
-      ?.value
+    const value = this.parent?.system.skills?.[`${this.itemIdentifier}`]?.value
```
Comment (kwitczak) [inline module/items/skill/data.js:128]: This error was affecting not only the display on the sheet, but also dice rolls.

File: module/actors/actor.js [hunk 2]
```diff
@@ -94,12 +94,8 @@ export class CoCActor extends Actor {
...
       this.system.skills = {}
       for (const i of this.items) {
-        if (i.type === 'skill') {
-          this.system.skills[`${i.system.skillName}`] = {
-            value: i.rawValue
-          }
-          this.system.skills[`${i.id}`] = { value: i.rawValue }
-        }
+        if (i.type !== 'skill') continue
+        this.system.skills[`${i.itemIdentifier}`] = { value: i.rawValue }
```
Comment (kwitczak) [inline module/actors/actor.js:98]: My worry is that I didn't found all of the usages where `itemIdentifier` should be used (both getters and setts) across the module...

**Comment by kwitczak** [comment]
@snap01 , @HavlockV I added quite a big description because I'm uncertain if this change won't break backwards-compatibility due to `id` usage and I'm slowly learning the system. I plan to do some more testing later during the week.

**Comment by kwitczak** [comment]
@snap01 I did some testing and it seems fine.
